### ISSUE TITLE
Unable to find the executed symbols in bloc 

### ISSUE THREAD

**Issue by bhavyapulagam839** [anwala/bloc#5]
BLOC Alphabets (Code vs. Paper)
More alphabets are implemented here compared to the BLOC paper ([A General Language for Modeling Social Media Account Behavior](http://arxiv.org/abs/2211.00639)). Specifically, this BLOC tool implements these [alphabets](https://github.com/anwala/bloc/blob/main/blob/main/bloc/symbols.json):

<img width="1459" alt="Screenshot 2024-04-15 at 2 13 22 PM" src="https://github.com/anwala/bloc/assets/113796526/eaf6a530-ff4e-4f62-9610-a9dfddf0194b">

**Comment by anwala** [comment]
Hello @bhavyapulagam839,

I think you provided an incorrect link to the BLOC default symbols: [https://github.com/anwala/bloc/blob/main/blob/main/bloc/symbols.json](https://github.com/anwala/bloc/blob/main/blob/main/bloc/symbols.json).

It should be: [https://github.com/anwala/bloc/blob/main/bloc/symbols.json](https://github.com/anwala/bloc/blob/main/bloc/symbols.json)

**Comment by bhavyapulagam839** [comment]
I have used the direct url provided in the readme file. Thank you for the clarification!

**Comment by filmenczer** [comment]
Thanks! @anwala could you please fix the link in the readme file?

**Comment by anwala** [comment]
Done. Thanks @filmenczer & @bhavyapulagam839.
